QT       -= core
QT       -= gui

TEMPLATE = lib

DEFINES += DFI_USE_CUSTOM_SHARED_MUTEX
DEFINES += RW_MUTEX_PRIORITIES

QMAKE_CXXFLAGS += -std=c++20 -fPIC -Wno-unused-function
QMAKE_CXXFLAGS_RELEASE -= -O2
QMAKE_CXXFLAGS_RELEASE += -O3
QMAKE_CFLAGS_RELEASE -= -O2
QMAKE_CFLAGS_RELEASE += -O3

SOURCES += \
    libmain.cpp
